Repository wecode-bootcamp-korea/38-2nd-GoodPlace-backend, pull requests merged in 2022-11, with the labels that each got.

#1 초기세팅 완료
  .env.sample
  .gitignore
  app.js
  models/dataSource.js
  package-lock.json
  package.json
  routes/index.js
  utils/error.js
Labels: 멘토 리뷰 요청

#2 [ADD] migration
  db/migrations/20221031120531_order_statuses.sql
  db/migrations/20221031120540_sellers.sql
  db/migrations/20221031120554_main_categories.sql
  db/migrations/20221031120603_sub_categories.sql
  db/migrations/20221031120731_products.sql
  db/migrations/20221031120740_product_images.sql
  db/migrations/20221031120753_users.sql
  db/migrations/20221031120819_options.sql
  db/migrations/20221031120820_rooms.sql
  db/migrations/20221031120833_room_images.sql
  db/migrations/20221031120849_orders.sql
  db/migrations/20221031120903_reviews.sql
  db/migrations/20221031120910_review_images.sql
  db/migrations/20221031120920_review_comments.sql
  db/migrations/20221102025158_rooms_options.sql
Labels: 멘토 리뷰 요청

#3 [MODIFY] migration
  .env.sample
  .gitignore
  db/migrations/01_order_statuses.sql
  db/migrations/02_users.sql
  db/migrations/03_sellers.sql
  db/migrations/04_main_categories.sql
  db/migrations/05_sub_categories.sql
  db/migrations/06_products.sql
  db/migrations/07_product_images.sql
  db/migrations/08_options.sql
  db/migrations/09_rooms.sql
  db/migrations/10_room_images.sql
  db/migrations/11_orders.sql
  db/migrations/12_reviews.sql
  db/migrations/13_review_images.sql
  db/migrations/14_review_comments.sql
  db/migrations/15_rooms_options.sql
Labels: 완료

#4 [ADD] user endpoint 기능 구현
  controllers/userController.js
  models/userDao.js
  package-lock.json
  package.json
  routes/index.js
  routes/userRouter.js
  services/userService.js
Labels: 완료

#9 [ADD] 리뷰 기능 CRUD
  .env.sample
  controllers/reviewController.js
  models/dataSource.js
  models/reviewDao.js
  models/userDao.js
  package-lock.json
  package.json
  routes/index.js
  routes/reviewRouter.js
  services/reviewService.js
  utils/auth.js
  utils/imageUploader.js
Labels: 멘토 리뷰 요청

#5 [ADD] product list 기능 구현
  .gitignore
  controllers/productController.js
  models/enum.js
  models/functionForProduct.js
  models/productDao.js
  routes/index.js
  routes/productRouter.js
  services/productService.js
Labels: 멘토 리뷰 요청

#11 [hotfix] product 필터링 기능 중 price filter 오탈자 수정
  models/functionForProduct.js
Labels: 멘토 리뷰 요청

#7 [ADD] 구매하기 api 구현 완료 ( 프론트 분들 요청사항 수정 반영 완료 )
  controllers/orderController.js
  models/enums.js
  models/orderDao.js
  package-lock.json
  routes/index.js
  routes/orderRouter.js
  services/orderService.js
Labels: 완료

#12 [hotfix] 리뷰 조회에서 대댓글 내용 항목 추가
  models/reviewDao.js
Labels: 완료

#8 [ADD] product main/list 기능 구현
  controllers/productController.js
  models/enum.js
  models/enums.js
  models/functionForProduct.js
  models/orderDao.js
  models/productDao.js
  package-lock.json
  routes/productRouter.js
  services/orderService.js
  services/productService.js
Labels: 수정 요청

#13 [hotfix] order 요청 형식 변경
  controllers/orderController.js
  controllers/reviewController.js
  models/orderDao.js
  models/productDao.js
  routes/orderRouter.js
  services/orderService.js
  utils/auth.js
Labels: 완료

#10 [리뷰의 comments 기능 구현 완료
  controllers/commentsController.js
  models/commentsDao.js
  models/reviewDao.js
  routes/commentsRouter.js
  routes/index.js
  services/commentsService.js
  services/orderService.js
Labels: 완료
